### ISSUE TITLE
Can I use custom environment variables？

### ISSUE THREAD

**Issue by NICK-DUAN** [Kong/kong-pongo#133]

**Comment by Tieske** [comment]
Can you please provide a more detailed description of your use case. The problem you run into, and how you consider resolving it?

**Comment by Tieske** [comment]
ping?

**Comment by NICK-DUAN** [comment]
Hey @Tieske , Like this:

02-access_spec.lua
```lua
local env = require "resty.env"

for _, strategy in helpers.each_strategy() do
  describe(PLUGIN_NAME .. ": (access) [#" .. strategy .. "]", function()
      -- some code
      env.set("IAM_DOMAIN", "http://9.148.165.39:8081")
      env.set("IAM_AUTH", "/authorization")
      -- some code
  end)
end
```

My plugin access.lua
```lua
-- some code
local iam_domain  = os.getenv("IAM_DOMAIN")
local iam_auth    = os.getenv("IAM_AUTH")
-- some code
```

I'm using Kubernetes to deploy kong, then I will get some variables from environment variables, like the code in my plugin. But when I do unit test, I will use different config.

**Comment by Tieske** [comment]
you should be able to use `helpers.setenv(name, value)`

The Kong workers will not be able to read the variables though, since nginx shields env variables. I think you can only read the env vars on module level, which executes on startup (in `init` phase) which still runs as the master process.

**Comment by NICK-DUAN** [comment]
Thank you, it works.

And I have another question. In my team, there are some hard codes that we check for, and one of them is `IP`. So I want to make a config file to save these variables, but I can't use it when unit-testing.

Could you give me a advice?

**Comment by Tieske** [comment]
sorry I didn't get the question? Can you be more specific?

**Comment by NICK-DUAN** [comment]
For example:

02-access_spec.lua
```lua

for _, strategy in helpers.each_strategy() do
  describe(PLUGIN_NAME .. ": (access) [#" .. strategy .. "]", function()
    -- some code
    
    file = io.open (configFilePath, "r")
    local envTab = {};
    for line in io.lines("main.lua") do
      table.insert(envTab, line)
    end
    helpers.setenv("IAM_DOMAIN", envTab[1])
    helpers.setenv("IAM_AUTH", envTab[2])

    -- some code
  end)
end
```

My problem is I do not know where to put this this config file. I've tried a lot of things, but they don't seem to load.

This is my unit test structure.
```Bash
spec
├── coding-session-handler
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── coding-token-handler
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── enhanced-service-token
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── service-token
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── signing
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
└── tencent-smartgate-auth
    ├── 01-schema_spec.lua
    └── 02-access_spec.lua
spec_ex/
├── coding-csrf-handler
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── coding-external-token
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── project-mapping
├── saas-auth
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
├── super-key
│   ├── 01-schema_spec.lua
│   └── 02-access_spec.lua
└── verify-dq-gateway
    ├── 01-schema_spec.lua
    └── 02-access_spec.lua
kong-plugin-myplugin-0.1.0-1.rockspec
```

**Comment by Tieske** [comment]
you can workaround this by using the debug library to find the location of the currently executing test file, then from there use a relative path to find the file.

I just created this PR on busted to do exactly that: https://github.com/Olivine-Labs/busted/pull/646 you can probably copy-paste some code from that as a workaround.

**Comment by NICK-DUAN** [comment]
Ok，thank you. I'll close this issue to follow your PR.
