### ISSUE TITLE
New variables like KONG_IMAGE for other dependencies

### ISSUE THREAD

**Issue by saeed617** [Kong/kong-pongo#137]
Pulling images from the docker hub is not possible in all places (our ci/cd can only pull images from the private registry). setting a variable for the other dependencies like Postgres, Cassandra, etc will fix this issue.

**Comment by Tieske** [comment]
Can you explain in a little more detail what you'd expect Pongo to do? How this is exactly supposed to work?

**Comment by Tieske** [comment]
thinking out loud here; can't you (before starting Pongo), use some docker command to pull the images locally from whatever repo you need? if they are local Pongo should pick them up without trying to pull them again no?

**Comment by saeed617** [comment]
Yes, I can pull them locally and tag them with the proper name and version :))
thanks for your quick response. I'm closing this.
