### ISSUE TITLE
plugin not enabled

### ISSUE THREAD

**Issue by halamajan** [Kong/kong-pongo#138]
Hi,
first of all thanks for great tooling.

I got following error when running plugin tests:

```
Plugin: token-auth (access) setup
/kong-plugin/spec/token-auth/01-access_spec.lua:41: [postgres] schema violation (name: plugin 'token-auth' not enabled; add it to the 'plugins' configuration property)
```

If I enable plugin manually by editing kong_tests.conf inside docker, I am able to run tests.

`sed -i '/plugins/ s/$/,token-auth/' spec/kong_tests.conf `

Did I miss something in setup procedure?

Regards,

Jan

**Comment by Tieske** [comment]
Have a look at the [template plugin](https://github.com/Kong/kong-plugin). Specifically how Kong is started for the tests: https://github.com/Kong/kong-plugin/blob/master/spec/myplugin/02-integration_spec.lua#L28-L35

**Comment by halamajan** [comment]
Thank you Tieske!
