### ISSUE TITLE
Gitlab CI

### ISSUE THREAD

**Issue by halamajan** [Kong/kong-pongo#139]
Hi there!

I want to run plugin tests in Gitlab CI. My question is: Is it possible to run kong-pongo in Gitlab runner with Docker socket binding configuration (as described [here](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-socket-binding))

CI job which I want to run `kong-pongo` script is docker container executed by Docker runner with following arguments:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -it docker:compose
```

There is problem because checkouted plugin repository is inside docker container and docker engine is running in host (Gitlab runner). Then I get following error message:

``` sh
/kong-plugin # pongo run
Creating kong-pongo_kong_run ... done
Error response from daemon: Mounts denied: 
The path /kong-plugin is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info.
```

Regards,

Jan

**Comment by halamajan** [comment]
The solution si probably to use dind runner https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-the-docker-image-docker-in-docker

**Comment by Tieske** [comment]
have you tried the docker-in-docker instructions? see https://github.com/Kong/kong-pongo#running-pongo-in-docker

**Comment by halamajan** [comment]
Sorry I missed that section the documentation. Thank you.

**Comment by Tieske** [comment]
What were you looking for? can we improve the docs by changing the header?

**Comment by Tieske** [comment]
maybe we should change it to "docker-in-docker" instead of "pongo in docker"

**Comment by halamajan** [comment]
I was focused on section https://github.com/Kong/kong-pongo#setting-up-ci (which is Travis specific IMHO), and just missed this one.

**Comment by halamajan** [comment]
> maybe we should change it to "docker-in-docker" instead of "pongo in docker"
I do not think that you the section is about "docker-in-docker", because what are you proposing is do Docker socket binding to the host which is not docker-in-docker.

**Comment by halamajan** [comment]
As explained here: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by Tieske** [comment]
That link is also in the "Running pongo in docker" section.

**Comment by Tieske** [comment]
I'll probably add link to the ci section then
