### ISSUE TITLE
Update the kong pongo git url 

### ISSUE THREAD

**Issue by piyushpgupta** [Kong/kong-pongo#140]
Please update the kong-pongo git clone url to 
git clone https://github.com/Kong/kong-pongo.git ,

from git clone git@github.com:Kong/kong-pongo.git 

all users might not able to clone from it .

**Comment by Tieske** [comment]
what is the problem?

**Comment by piyushpgupta** [comment]
Permission denied when cloning from the git@github.com:Kong/kong-pongo.git

**Comment by Tieske** [comment]
shouldn't that be identical? I've never seen that. Any links to docs?

also what references should be updated?

**Comment by piyushpgupta** [comment]
@Tieske  The document mention the git clone url as 
git clone git@github.com:Kong/kong-pongo.git

when users try to clone it , they get permission denied as mentioned in the attachment .

Instead of this we can mention http/s url to clone so that no user will face issue related to permission 
<img width="738" alt="Screenshot 2021-01-13 at 19 22 22" src="https://user-images.githubusercontent.com/10510661/104439806-e21e5b00-55d4-11eb-8048-b56a4c4c3548.png">

**Comment by piyushpgupta** [comment]
@Tieske  adding more details these git clone URL , require update

https://github.com/Kong/kong-pongo#installation
change git clone git@github.com:Kong/kong-pongo.git to 
https://github.com/Kong/kong-pongo.git 
as step to add ssh key is missing  or we have to add step to add ssh key from github

same update goes for : https://github.com/Kong/kong-pongo#do-a-test-run
where git clone git@github.com:Kong/kong-plugin.git  require change .

same updates goes for : https://github.com/Kong/kong-pongo#pongo-on-windows
where git clone git@github.com:Kong/kong-pongo.git require update

In this section we are using correct git clone URL 
https://github.com/Kong/kong-pongo#a-walkthrough

**Comment by Tieske** [comment]
ok thx, would you mind sending a PR?

**Comment by piyushpgupta** [comment]
Hi @Tieske  i added new PR for the changes 
https://github.com/Kong/kong-pongo/pull/144
