### ISSUE TITLE
Proper plugin configuration for development and/or CI/CD

### ISSUE THREAD

**Issue by eladbs** [Kong/kong-pongo#145]
Hi,
In order for a plugin to be available in Kong we need to edit the `kong_tests.conf` file. and add, for i.e.:
```
plugins=bundled,dummy,rewriter,my-plugin
```
then we would have to rebuild the test images, run test, etc.

What's the correct process (or best practice) of editing this file in a CI/CD with many plugins?
And to specific extent, when developing plugins. How would you configure such thing? Do I really need to configure and rebuild it every time I switch plugins?

Thanks!
Elad.

**Comment by Tieske** [comment]
imo each plugin should be on its own. Hence for testing in CI, you'd not need the other plugins.

The plugins to load can be dynamically set in the tests, see https://github.com/Kong/kong-plugin/blob/master/spec/myplugin/02-integration_spec.lua#L34

hth

**Comment by eladbs** [comment]
Thanks for the fast reply!

Correct me if I'm wrong, but isn't the file `kong_tests.conf` configured globally on the CI/CD server rather than per build?

I configured like you suggested and it works for the plugin I work on. 
The "plugins" config in the `kong_tests.conf` file instructs Pongo to bundle the plugins into the test image, right? 
Where do it takes them from? 
I guess I'm lacking some knowledge on the subject.

**Comment by Tieske** [comment]
as many opinions as people 😄 

My 2cts: the plugin code should be bundled with its tests, and all of the setup/mocks/whatever needed to test that plugin. If any of this would not be in the repo for the plugin, then you risk getting brittle tests (if someone updates one repo (your plugin) without updating the other (the repo containing your `kong_test.conf`)).

If however you want to generate additional tests, integrating an entire Kong installation, with multiple plugins, and whatever backends, IDP's and what not, that would be a separate set of tests with a wider scope than just the plugin tests.
This would be out of scope for Pongo.

**Comment by eladbs** [comment]
Ha yes.. too many :D 

Let's say then I will test each plugin on its own.
Then the correct way should be like in docs [https://github.com/Kong/kong-pongo#setting-up-ci](url) but add another step and add my plugin to the "plugins" config in the `kong_test.conf` file, right?

**Comment by Tieske** [comment]
no, that shouldn't be necessary (updating `kong_test.conf`), just do as the template repo does: https://github.com/Kong/kong-plugin/blob/master/spec/myplugin/02-integration_spec.lua#L34

**Comment by eladbs** [comment]
Wow... it works without it... We were struggling for a few days now configuring and understanding how it work and we must have understood it wrong.
Thanks a lot! I really appreciate that!

**Comment by Tieske** [comment]
just in general, when writing new plugins, start with the plugin template, it has all the proper defaults and best-practices.

**Comment by eladbs** [comment]
That's we'll do. Learnt it the hard way...
Thanks!
