### ISSUE TITLE
pongo logs out of docker registries

### ISSUE THREAD

**Issue by eskerda** [Kong/kong-pongo#148]
pongo does `docker logout` from the registry if set. Is there any security reason for logging out of the docker registry other than cleaning up?

```
$ git grep "docker logout"
pongo.sh:389:          docker logout $NIGHTLY_EE_DOCKER_REPO
pongo.sh:395:          docker logout $NIGHTLY_EE_DOCKER_REPO
pongo.sh:399:        docker logout $NIGHTLY_EE_DOCKER_REPO
pongo.sh:422:            docker logout $KONG_EE_REPO
pongo.sh:428:            docker logout $KONG_EE_REPO
pongo.sh:432:          docker logout $KONG_EE_REPO
```

Maybe worth adding a `--no-logout` option, or an env that can be set to `DOCKER_DO_LOGOUT=0`.

**Comment by Tieske** [comment]
it only logs out if it had to log in

**Comment by eskerda** [comment]
there's a slight corner case where:

1. I am logged in
2. I did set an incorrect image name
3. it logs me out when it fails to pull that image

**Comment by Tieske** [comment]
As shown in the OP, the logout is for 2 repo's, KONG_EE (currently Bintray), and the repo for the NIGHTLY builds of EE.

What other repo do we need currently?
