### ISSUE TITLE
Add possibility to install custom package in the docker image

### ISSUE THREAD

**Issue by Elyahou** [Kong/kong-pongo#154]
I want to test a plugin that have `lrexlib-pcre2` dependency.

This dependency require to have header file for PCRE2 installed.... and thus pongo fail to run such test... I think pongo lack the ability to have custom packages installed

**Comment by Tieske** [comment]
have you tried adding a setup script; `.pongo/pongo-setup.sh`? see https://github.com/Kong/kong-pongo#test-initialization

**Comment by Elyahou** [comment]
@Tieske Thanks !

Fixed by adding such file with this content:
```
apk add pcre2-dev
find /kong-plugin -maxdepth 1 -type f -name '*.rockspec' -exec luarocks install --only-deps {} \;
```
