### ISSUE TITLE
How can I run tests against a redis cluster?

### ISSUE THREAD

**Issue by alexey-nextreason** [Kong/kong-pongo#161]
I'm developing a kong plugin that needs to use a redis cluster. But there's no way to specify redis image when running pongo only redis version. Is there a plan to add that configuration setting to the pongo tool? 
Thank you!

**Comment by Tieske** [comment]
You can create your own custom dependencies, see https://github.com/Kong/kong-pongo#custom-local-dependencies

Essentially you have to provide a docker-compose snippet for the dependency.

**Comment by alexey-nextreason** [comment]
Thank you very much for that idea!

**Comment by Tieske** [comment]
@alexey-nextreason if you don't mind, would you please post your results here?

**Comment by alexey-nextreason** [comment]
worked like a charm with this compose snippet and using resty-redis-cluster lua package
`version: '3.5'

services:
  redis-cluster:
    image: 'grokzen/redis-cluster:latest'
    environment:
      INITIAL_PORT: 6379
    ports:
      - "6379:6379"
      - "7000-7005:7000-7005"
    healthcheck:
      interval: 1s
      retries: 30
      test:
      - CMD
      - redis-cli
      - ping
      timeout: 3s
    restart: on-failure
    stop_signal: SIGKILL
    networks:
      - ${NETWORK_NAME}`
