### ISSUE TITLE
Improve the docker login logic

### ISSUE THREAD

**Issue by aboudreault** [Kong/kong-pongo#178]
* Perform the docker login if the credentials are present and then docker logout after Pongo completes execution of the docker pull. This would allow for increased docker pull rate-limiting using certain docker user accounts.

* if given we should log in, if not given we should try without. If it fails, we should retry with the private creds for EE images not publicly available (eg. 036-2 and the likes).

**Comment by Tieske** [comment]
to be taken into account: the docker login should not only wrap pulling the Kong image, but all pulls. eg. when doing "pongo up" it will pull cassandra and postgres. This will minimize the rate-limit errors which we're still encountering.

**Comment by Tieske** [comment]
this has been fixed
