### ISSUE TITLE
Running pongo as non-root

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-pongo#236]
I would like to be able to run pongo as a non-root user but it seems to generally run into problems creating directories.
This is a bit of a problem for us in CI (any ci that doesn't use container based runners) as it tests to leave files + directories on the host that are owned by root and can't be removed.

This basically requires a human to ssh onto the build boxes and manually remove files.

I think (I haven't tried) one can get around this by running clean up steps 

```sh
pongo rm -rf /kong-plugin/serveroot
pongo rm -rf /kong-plugin/<test reports>
```
But even that doesn't always work. 

Work-arounds are ok for a bit, but we really don't want to be running things as a root user anywhere, even if in a container.

**Comment by origama** [comment]
@esatterwhite this issue has been closed without any comment. I am currently facing this problem: 
* my job in the CI runs as non-root `ci-user` 
* the job is creating the serveroot folder as root
* at the next iteration it is not able to delete the serveroot folder

I am not sure why pongo creates only that folder as root

**Comment by esatterwhite** [comment]
I don't remember why I closed it. Feel free to reopen or make a new issue.

**Comment by origama** [comment]
@esatterwhite I am not a collaborator hence I cannot reopen this issue, I just opened #534
