### ISSUE TITLE
Run Kong Pongo on centos (without docker)

### ISSUE THREAD

**Issue by chetan193** [Kong/kong-pongo#280]
Is there any way where we can run kong pongo on a centos machine without docker

I have explored the docker in docker way, but since my application would be using the CI pipeline, it would create a problem

Any suggestion or recommended way is really appreciated

**Comment by Tieske** [comment]
Pongo runs its tests inside a dockercontainer and uses docker-compose to setup the environment, so you really need docker.

> I have explored the docker in docker way, but since my application would be using the CI pipeline, it would create a problem

why would it be a problem?

**Comment by Tieske** [comment]
since CentOS is EOL, closing this.
