### ISSUE TITLE
(docs) needs example .travis.yml files for kong and kong-ee

### ISSUE THREAD

**Issue by kikito** [Kong/kong-pongo#29]
If they are small enough, it might be enough to put them in a "Using Pongo in CI" section in the README.

Alternatively, Pongo itself could have one or two .travis.yml file which actually run CI on this repo, perhaps using a [dummy plugin](https://github.com/Kong/kong-plugin-uppercase-response).

**Comment by Tieske** [comment]
why did you create the dummy plugin? there already was the template plugin: https://github.com/Kong/kong-plugin or did I miss something?

**Comment by Tieske** [comment]
I think using it for CI definitely is a good idea. Giving it a first go shouldn't be very hard.

Optimizing it and caching the generated docker images, so they do not have to be generated over and over again would be more work probably.

**Comment by kikito** [comment]
I created the dummy plugin for my Kong Summit presentation (we wanted to talk about deployments in the context of custom plugins, so we created a custom plugin just for that purpose).

> there already was the template plugin

I missed this! When I have needed to build a new plugin in the past, I just copied an existing one. Like a peasant 😂.

**Comment by Tieske** [comment]
closing this, has been implemented 🎉
