### ISSUE TITLE
`pongo nuke`

### ISSUE THREAD

**Issue by kikito** [Kong/kong-pongo#30]
It seems that `pongo clean` is similar in features to `gojira nuke`. Could it be renamed to `pongo nuke` then?

**Comment by Tieske** [comment]
I prefer `clean`, but it should be easy to add it as an alias?

**Comment by kidd** [comment]
This asks for a `.pongorc` file already. /s

**Comment by Tieske** [comment]
not sure what that would do... there already is `.pongo-setup.sh`, but that's related to a test-run, not Pongo itself.

**Comment by kidd** [comment]
it was a (badly explaiend) joke, nvm :)
