### ISSUE TITLE
pongo warnings about deprecated Penlight modules

### ISSUE THREAD

**Issue by chazdnato** [Kong/kong-pongo#301]
Every run of our test suite now has this message intermixed throughout:

```
2022/07/12 14:54:07 [warn] [Penlight 1.12.0] the contents of module 'pl.text' has moved into 'pl.stringx' (deprecated after 1.11.0, scheduled for removal in 2.0.0)
```

This appears to be due to `local pl_text = require "pl.text"` directives in all the `kong-versions/*/kong/spec/fixtures/https_server.lua` files.

I could do a PR to simply update this, but am not nearly familiar enough with with the Penlight code to know if this is a simple search/replace.

Thanks!

**Comment by chazdnato** [comment]
I was able to prevent these warnings from happening by editing the appropriate fixture file, and replacing `pl.text` with `pl.stringx`:

```
❯ git diff kong-versions/2.8.1/kong/spec/fixtures/https_server.lua
diff --git a/kong-versions/2.8.1/kong/spec/fixtures/https_server.lua b/kong-versions/2.8.1/kong/spec/fixtures/https_server.lua
index 550f512..8e02a0d 100644
--- a/kong-versions/2.8.1/kong/spec/fixtures/https_server.lua
+++ b/kong-versions/2.8.1/kong/spec/fixtures/https_server.lua
@@ -9,7 +9,7 @@ local pl_dir = require "pl.dir"
 local pl_file = require "pl.file"
 local pl_template = require "pl.template"
 local pl_path = require "pl.path"
-local pl_text = require "pl.text"
+local pl_text = require "pl.stringx"
 local uuid = require "resty.jit-uuid"
```

```
KONG_VERSION=2.8.1 pongo run
```

I get no warnings in this scenario. Are those `versions/*/kong/spec/fixtures` files auto-generated? I could not find any references to `pl.text` in Kong's main github: https://github.com/Kong/kong/search?q=pl.text (compare to https://github.com/Kong/kong-pongo/search?q=pl.text)

**Comment by Tieske** [comment]
Yes they get generated. They are copied over from the Kong source repo. Hence what I mentioned before; it should be fixed upstream.

**Comment by Tieske** [comment]
it has already been fixed; https://github.com/Kong/kong/blob/master/spec/fixtures/https_server.lua#L12

But as mentioned; everything is pulled into Pongo from the Kong repo. So for older versions of Kong it will pull those old tags, and those will still have the old code. No way to fix that.

If you really want to get rid of those messages (for your own use) you could write a test-initialization script that would replace the line inside the actual test image.

**Comment by chazdnato** [comment]
Ah, that's why I couldn't find it!! Thank you. We are (relatively) closely following Kong releases, so this will resolve itself as we upgrade. I appreciate the extra help here!
