### ISSUE TITLE
i have a problem when build pongo

### ISSUE THREAD

**Issue by Canon4G** [Kong/kong-pongo#308]
macOS 12.0.1
i build pongo follow the doc

i user command 'pongo run' in kong-api-version-plugin 

response me: 

[pongo-INFO] image 'kong-pongo-test:2.8.1' not found, auto-building it
[pongo-INFO] starting build of image 'kong-pongo-test:2.8.1'
Sending build context to Docker daemon    109MB
Step 1/17 : ARG KONG_BASE
Step 2/17 : FROM ${KONG_BASE}
 ---> bf394ffed022
Step 3/17 : ARG KONG_DEV_FILES
 ---> Using cache
 ---> 4a1c6a40085f
Step 4/17 : COPY $KONG_DEV_FILES /kong
 ---> Using cache
 ---> 972aac9f0dd4
Step 5/17 : COPY assets/busted_helper.lua        /pongo/busted_helper.lua
 ---> Using cache
 ---> f22897d2e6ae
Step 6/17 : COPY assets/pongo_entrypoint.sh      /pongo/pongo_entrypoint.sh
 ---> Using cache
 ---> 48ba816c19f7
Step 7/17 : COPY assets/default-pongo-setup.sh   /pongo/default-pongo-setup.sh
 ---> Using cache
 ---> bea0b3623b2c
Step 8/17 : COPY assets/pongo_pack.lua           /pongo/pongo_pack.lua
 ---> Using cache
 ---> 9e182775d5bc
Step 9/17 : COPY assets/kong_migrations_start.sh /pongo/kong_migrations_start.sh
 ---> Using cache
 ---> 311d83593b11
Step 10/17 : COPY assets/kong_start_dbless.sh     /pongo/kong_start_dbless.sh
 ---> Using cache
 ---> 0dc491397ece
Step 11/17 : COPY assets/parse_git_branch.sh      /pongo/parse_git_branch.sh
 ---> Using cache
 ---> 50950014fc0d
Step 12/17 : COPY assets/pongo_profile.sh         /etc/profile.d/pongo_profile.sh
 ---> Using cache
 ---> d1449232b9a7
Step 13/17 : USER root
 ---> Using cache
 ---> c5ea66a20876
Step 14/17 : RUN apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov
 ---> Running in fc23930205d0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: network error (check Internet connection and firewall)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: network error (check Internet connection and firewall)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
2 errors; 40 distinct packages available
/bin/sh: make: not found
The command '/bin/sh -c apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov' returned a non-zero code: 127
[pongo-ERROR] Error: failed to build test environment
guanhao@localhost:~/kong-api-version-plugin$apk
-bash: apk: command not found
guanhao@localhost:~/kong-api-version-plugin$brew apk
Error: Unknown command: apk
guanhao@localhost:~/kong-api-version-plugin$pongo run --no-cassandra
[pongo-INFO] image 'kong-pongo-test:2.8.1' not found, auto-building it
[pongo-INFO] starting build of image 'kong-pongo-test:2.8.1'
Sending build context to Docker daemon    109MB
Step 1/17 : ARG KONG_BASE
Step 2/17 : FROM ${KONG_BASE}
 ---> bf394ffed022
Step 3/17 : ARG KONG_DEV_FILES
 ---> Using cache
 ---> 4a1c6a40085f
Step 4/17 : COPY $KONG_DEV_FILES /kong
 ---> Using cache
 ---> 972aac9f0dd4
Step 5/17 : COPY assets/busted_helper.lua        /pongo/busted_helper.lua
 ---> Using cache
 ---> f22897d2e6ae
Step 6/17 : COPY assets/pongo_entrypoint.sh      /pongo/pongo_entrypoint.sh
 ---> Using cache
 ---> 48ba816c19f7
Step 7/17 : COPY assets/default-pongo-setup.sh   /pongo/default-pongo-setup.sh
 ---> Using cache
 ---> bea0b3623b2c
Step 8/17 : COPY assets/pongo_pack.lua           /pongo/pongo_pack.lua
 ---> Using cache
 ---> 9e182775d5bc
Step 9/17 : COPY assets/kong_migrations_start.sh /pongo/kong_migrations_start.sh
 ---> Using cache
 ---> 311d83593b11
Step 10/17 : COPY assets/kong_start_dbless.sh     /pongo/kong_start_dbless.sh
 ---> Using cache
 ---> 0dc491397ece
Step 11/17 : COPY assets/parse_git_branch.sh      /pongo/parse_git_branch.sh
 ---> Using cache
 ---> 50950014fc0d
Step 12/17 : COPY assets/pongo_profile.sh         /etc/profile.d/pongo_profile.sh
 ---> Using cache
 ---> d1449232b9a7
Step 13/17 : USER root
 ---> Using cache
 ---> c5ea66a20876
Step 14/17 : RUN apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov
 ---> Running in 031caf9a79b0
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/main: network error (check Internet connection and firewall)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.16/community: network error (check Internet connection and firewall)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: No such file or directory
2 errors; 40 distinct packages available
/bin/sh: make: not found
The command '/bin/sh -c apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov' returned a non-zero code: 127
[pongo-ERROR] Error: failed to build test environment
guanhao@localhost:~/kong-api-version-plugin$po
pod2html         pod2man5.18      pod2text         pod2usage5.30    podselect5.18    post-grohtml     postfix          postmap          power_report.sh
pod2html5.18     pod2man5.30      pod2text5.18     podchecker       podselect5.30    postalias        postgres         postmaster       powermetrics
pod2html5.30     pod2readme       pod2text5.30     podchecker5.18   policytool       postcat          postkick         postmulti
pod2latex        pod2readme5.18   pod2usage        podchecker5.30   pongo            postconf         postlock         postqueue
pod2man          pod2readme5.30   pod2usage5.18    podselect        popd             postdrop         postlog          postsuper
guanhao@localhost:~/kong-api-version-plugin$pongo

                /~\
  ______       C oo
  | ___ \      _( ^)
  | |_/ /__  _/__ ~\ __   ___
  |  __/ _ \| '_ \ / _ `|/ _ \
  | | | (_) | | | | (_| | (_) |
  \_|  \___/|_| |_|\__, |\___/
                    __/ |
                   |___/  v1.1.0

Usage: pongo <action> [--help] [options...] [--] [action options...]

Options (can also be added to '.pongo/pongorc'):
  --no-cassandra     do not start cassandra db
  --no-postgres      do not start postgres db
  --grpcbin          do start grpcbin (see readme for info)
  --redis            do start redis db (see readme for info)
  --squid            do start squid forward-proxy (see readme for info)

Project actions:
  init          initializes the current plugin directory with some default
                configuration files if not already there (not required)

  lint          will run the LuaCheck linter

  pack          will pack all '*.rockspec' files into '*.rock' files for
                distribution (see LuaRocks package manager docs)

  run           run spec files, accepts Busted options and spec files/folders
                as arguments, see: 'pongo run -- --help'

  shell         get a shell or run a command directly on a kong container

  tail          starts a tail on the specified file. Default file is
                ./servroot/logs/error.log, an alternate file can be specified

Environment actions:
  build         build the Kong test image, add '--force' to rebuild images

  clean / nuke  removes the dependency containers and deletes all test images

  docs          will generate and open the test-helper documentation

  down          remove all dependency containers

  expose        expose the internal ports for access from the host

  logs          show docker-compose logs of the Pongo environment

  restart       shortcut, a combination of; down + up

  status        show status of the Pongo network, images, and containers

  up            start required dependency containers for testing

Maintenance actions:
  update        update embedded artifacts for building test images

Environment variables:
  KONG_VERSION  the specific Kong version to use when building the test image
                (note that the patch-version can be 'x' to use latest)

  KONG_IMAGE    the base Kong Docker image to use when building the test image

  KONG_LICENSE_DATA
                set this variable with the Kong Enterprise license data

  POSTGRES_IMAGE   the Postgres image to use (default postgres:9.5)
  CASSANDRA_IMAGE  the Cassandra image to use (default cassandra:3.11)
  REDIS_IMAGE      the Redis dependency to use (default redis:6.2.6-alpine)
  SQUID_IMAGE      the Squid dependency to use (default sameersbn/squid:3.5.27-2)
  GRPCBIN_IMAGE    the Grpcbin dependency to use (default moul/grpcbin:latest)

Example usage:
  pongo run
  KONG_VERSION=1.3.x pongo run -v -o gtest ./spec/02-access_spec.lua
  POSTGRES_IMAGE=postgres:10 KONG_IMAGE=kong-ee pongo run
  pongo down

guanhao@localhost:~/kong-api-version-plugin$pongo run --no-cassandra
[pongo-INFO] image 'kong-pongo-test:2.8.1' not found, auto-building it
[pongo-INFO] starting build of image 'kong-pongo-test:2.8.1'
Sending build context to Docker daemon    109MB
Step 1/17 : ARG KONG_BASE
Step 2/17 : FROM ${KONG_BASE}
 ---> bf394ffed022
Step 3/17 : ARG KONG_DEV_FILES
 ---> Using cache
 ---> 4a1c6a40085f
Step 4/17 : COPY $KONG_DEV_FILES /kong
 ---> Using cache
 ---> 972aac9f0dd4
Step 5/17 : COPY assets/busted_helper.lua        /pongo/busted_helper.lua
 ---> Using cache
 ---> f22897d2e6ae
Step 6/17 : COPY assets/pongo_entrypoint.sh      /pongo/pongo_entrypoint.sh
 ---> Using cache
 ---> 48ba816c19f7
Step 7/17 : COPY assets/default-pongo-setup.sh   /pongo/default-pongo-setup.sh
 ---> Using cache
 ---> bea0b3623b2c
Step 8/17 : COPY assets/pongo_pack.lua           /pongo/pongo_pack.lua
 ---> Using cache
 ---> 9e182775d5bc
Step 9/17 : COPY assets/kong_migrations_start.sh /pongo/kong_migrations_start.sh
 ---> Using cache
 ---> 311d83593b11
Step 10/17 : COPY assets/kong_start_dbless.sh     /pongo/kong_start_dbless.sh
 ---> Using cache
 ---> 0dc491397ece
Step 11/17 : COPY assets/parse_git_branch.sh      /pongo/parse_git_branch.sh
 ---> Using cache
 ---> 50950014fc0d
Step 12/17 : COPY assets/pongo_profile.sh         /etc/profile.d/pongo_profile.sh
 ---> Using cache
 ---> d1449232b9a7
Step 13/17 : USER root
 ---> Using cache
 ---> c5ea66a20876
Step 14/17 : RUN apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov
 ---> Running in e5310442a8a5
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
v3.16.2-68-gee69069a4a [https://dl-cdn.alpinelinux.org/alpine/v3.16/main]
v3.16.2-70-g561c4577fc [https://dl-cdn.alpinelinux.org/alpine/v3.16/community]
OK: 17025 distinct packages available
(1/40) Installing bsd-compat-headers (0.7.2-r3)
(2/40) Installing curl (7.83.1-r2)
(3/40) Installing binutils (2.38-r3)
(4/40) Installing libgomp (11.2.1_git20220219-r2)
(5/40) Installing libatomic (11.2.1_git20220219-r2)
(6/40) Installing gmp (6.2.1-r2)
(7/40) Installing isl22 (0.22-r0)
(8/40) Installing mpfr4 (4.1.0-r0)
(9/40) Installing mpc1 (1.2.1-r0)
(10/40) Installing gcc (11.2.1_git20220219-r2)
(11/40) Installing musl-dev (1.2.3-r0)
(12/40) Installing libc-dev (0.7.2-r3)
(13/40) Installing g++ (11.2.1_git20220219-r2)
(14/40) Installing oniguruma (6.9.8-r0)
(15/40) Installing jq (1.6-r1)
(16/40) Installing m4 (1.4.19-r1)
(17/40) Installing make (4.3-r0)
(18/40) Installing openssl-dev (1.1.1q-r0)
(19/40) Installing libffi (3.4.2-r1)
(20/40) Installing gdbm (1.23-r0)
(21/40) Installing xz-libs (5.2.5-r1)
(22/40) Installing mpdecimal (2.5.1-r1)
(23/40) Installing sqlite-libs (3.38.5-r0)
(24/40) Installing python3 (3.10.5-r0)
(25/40) Installing py3-contextlib2 (21.6.0-r2)
(26/40) Installing py3-tomli (2.0.1-r1)
(27/40) Installing py3-pep517 (0.12.0-r2)
(28/40) Installing py3-six (1.16.0-r1)
(29/40) Installing py3-retrying (1.3.3-r3)
(30/40) Installing py3-appdirs (1.4.4-r3)
(31/40) Installing py3-more-itertools (8.13.0-r0)
(32/40) Installing py3-ordered-set (4.0.2-r3)
(33/40) Installing py3-parsing (2.4.7-r3)
(34/40) Installing py3-packaging (21.3-r0)
(35/40) Installing py3-setuptools (59.4.0-r0)
(36/40) Installing py3-pip (22.1.1-r0)
(37/40) Installing python3-dev (3.10.5-r0)
(38/40) Installing libunistring (1.0-r0)
(39/40) Installing libidn2 (2.3.2-r2)
(40/40) Installing wget (1.21.3-r0)
Executing busybox-1.35.0-r17.trigger
OK: 355 MiB in 80 packages
curl: (6) Could not resolve host: objects.githubusercontent.com
tar: invalid magic
tar: short read
make: /bin/sh: Operation not permitted
make: uname: Operation not permitted
make: dirname: Operation not permitted
make: /bin/sh: Operation not permitted
make: /bin/sh: Operation not permitted
make: *** [Makefile:133: bin/grpcurl] Error 127
The command '/bin/sh -c apk update     && apk add zip unzip make g++ py-pip jq git bsd-compat-headers m4 openssl-dev curl wget python3-dev     && curl -k -s -S -L https://github.com/fullstorydev/grpcurl/releases/download/v1.7.0/grpcurl_1.7.0_linux_x86_64.tar.gz | tar xz -C /kong/bin     && pip install httpie     ; cd /kong     && git config --global url.https://github.com/.insteadOf git://github.com/     && make dependencies     && luarocks install busted-htest     && luarocks install luacov' returned a non-zero code: 2
[pongo-ERROR] Error: failed to build test environment

**Comment by outsinre** [comment]
I see this line:

```
 curl: (6) Could not resolve host: objects.githubusercontent.com
```

Probably related to your network. Try again with VPN on?

**Comment by Canon4G** [comment]
> 

i can ping this host success， and i modify me hosts file but it not work

**Comment by Tieske** [comment]
any restrictions in your environment?

> make: /bin/sh: Operation not permitted

this looks like an older issue with Alpine. See https://github.com/Kong/kong-pongo/blob/master/README.md?plain=1#L6
make sure to use a recent docker version

**Comment by Tieske** [comment]
@Canon4G did you resolve the issue? what was the problem?

**Comment by Canon4G** [comment]
> @Canon4G did you resolve the issue? what was the problem?

i resolve my problem, thanks
