### ISSUE TITLE
allow to run tests against development versions of Kong

### ISSUE THREAD

**Issue by Tieske** [Kong/kong-pongo#32]
For example to run nightly tests against Kong `master` or `next`.

**Comment by Tieske** [comment]
Update: on the Pongo side this was implemented in #61, the wait was for the CE images to get the labels with git commit-id. Enterprise images are supported, but are Kong internal only.

These are now available, except for a typo in the label name 😞, (`org.opencontainers.revision` was added in stead of `org.opencontainers.image.revision`).

When the label is renamed then the following nightly builds will be available as test targets:

* `KONG_VERSION=nightly pongo run` --> will run tests against Kong CE, `master`
* `KONG_VERSION=nightly-ee pongo run` --> will run tests against Kong EE `master`

**Comment by Tieske** [comment]
@kidd @murillopaula @hutchic 

see above, 2 master images are available for testing plugins. What other images do we need or is this enough? do we need the `next` branches?

**Comment by Tieske** [comment]
@dndx adding you as well, since you asked about this recently iirc

**Comment by kidd** [comment]
We currently have nightlies for next/1.5.0.x, next/2.1.x.x , next/2.2.x.x  and soon we'll create next/2.3.x.x and we'll have nightlies for it too

I'd say all of them make more sense than testing against the already released images.  But if we're looking for the latest nightly, it the `next/*` with higher number. @eskerda can you confirm this? what's your take on this topic?

**Comment by kikito** [comment]
Given that we develop in topic branches and not on nightly versions, wouldn't it make more sense to have a KONG_BRANCH variable instead of a KONG_VERSION one? One which allowed us to do 

`KONG_BRANCH=my_topic_branch pongo run`

That's at least how I understand "test against development versions".

My usecase: I just merged a new feature in `kong/next`, and I need to use it in a plugin and run the tests. There doesn't seem to be a way to tell pongo to use `next`. I think this is a common situation while developing plugins along features needed by them in Kong.

**Comment by Tieske** [comment]
@kikito I've been thinking about that to. The `KONG_VERSION` is useful for customers that need to test against custom images we provided for them. But a feature to run against "branches" makes sense

So instead of the fixed `nightly` and `nightly-ee` tags that will pull master (of CE and EE respectively), we could implement pulling a tag. That would make the whole thing a lot more flexible I think.

**Comment by eskerda** [comment]
How would spec helpers be handled on the case of a moving target? Not much familiarized with the codebase anymore, but it should be possible to expose the path of the spec helpers (ie: a branch pulled) + an image and run without issues

**Comment by Tieske** [comment]
the docker images are labelled, see https://github.com/opencontainers/image-spec/blob/master/annotations.md

see https://github.com/search?q=org%3AKong+org.opencontainers.image.revision&type=code 

So when Pongo pulls a dev image, it will check the label, checkout the corresponding commit and add the test helpers from that commit.

**Comment by eskerda** [comment]
Oh cool, didn't remember that. So if we annotate our nightlies then we should be able to use pongo with them

**Comment by Tieske** [comment]
not yet, since it currently only recognizes the predefined labels "nightly" and "nightly-ee".

The issue I currently have is when an image name is specified that needs to =be pulled somewhere, how to determine whether it is a CE or EE image? because that determines the repo to pull from.
Of course we could try one first and then the other, but that would be a bit lame imo.

Ideas are welcome...

**Comment by Tieske** [comment]
aaaaaand... as I type that, we could use another label; `org.opencontainers.image.source` for example, which would point to either the Kong CE repo or Kong EE one. 

wdyt @hutchic @eskerda ?

**Comment by eskerda** [comment]
It should accept any arbitrary image name (if it's properly annotated to get the specs pongo wants). Any complex label matching / parsing will always end up blowing up, plus maintaining it is a chore.

For the cases that are not too complex (extra dependent services), this already does the thing for me:

```
GOJIRA_IMAGE=some-registry/kong-enterprise-edition:next-2.3.x.x-nightly-alpine
KONG_PLUGINS=name-of-plugin gojira up -t next/2.3.x.x --volume $(realpath path-to-plugin):/kong-plugin
gojira run -t next/2.3.x.x bin/busted -o htest /kong-plugin/spec
```

**Comment by Tieske** [comment]
since pongo support nightly and nightly-ee this can be closed now
