### ISSUE TITLE
Significant increase in time it takes to run tests on Ubuntu

### ISSUE THREAD

**Issue by nbialostosky** [Kong/kong-pongo#359]
### Summary

With the release of `2.0.0`, and the [breaking change of swapping to Ubuntu](https://github.com/Kong/kong-pongo/blob/master/README.md#changes), we saw a dramatic increase in the amount of time it took to execute our custom plugin tests when using Pongo.

We opted to pin to `1.3.0` as that allowed us to get back to our sub 2-minute run time. However, ideally, we'd like to remain up to date with the most recent items added to Pongo.

We believed the increase in time was part of having to install Python, and appears to be ([as this fix did speed things up](https://github.com/Kong/kong-pongo/pull/357)). However, we are still seeing a significant increase in the amount of time it takes to run these tests. Here is the overall run time of our CI job in the different scenarios:

| Scenario | Time |
| --- | --- |
| When pinned to `1.3.0` | 1m 58s |
| When forced to install Python | 7m 46s |
| No Python, currently whats on `master` | 5m 15s |

Specifically in regards to the test run times:

 Alpine: `50742.63 ms total` vs. Ubuntu: `235222.28 ms total`.

### Options

Would it be possible to support the ability to choose which image you want to run on? I.e. the default is Ubuntu, but i'd like to override that default to run on Alpine.

I attempted this, by hardcoding the `KONG_IMAGE` to `kong:2.8.1-alpine` in my `pongo run` -- however, it fails, as the default shell was also changed to `/bin/bash`.

```
Step 20/27 : RUN apt update     && apt install -y zip make jq m4 curl build-essential wget git libssl-dev zlib1g-dev
 ---> Running in 407cbc1f6756
/bin/sh: apt: not found
The command '/bin/sh -c apt update     && apt install -y zip make jq m4 curl build-essential wget git libssl-dev zlib1g-dev' returned a non-zero code: 127
[pongo-ERROR] Error: failed to build test environment
```

In addition, I'd ideally not like to have to pass in the Kong version into the image -- just specify `alpine` or `ubuntu` and it would do the right thing.

**Comment by hanshuebner** [comment]
I implemented the option to select an operating system a while ago (https://github.com/Kong/kong-pongo/commit/70c4d9d47df84118e9170a745e8f3b938535b511), but we felt that it would complicate pongo and the duplication of the Dockerfiles is a bit bothersome.  We suffer from the long build times ourselves and will try to address it in the near future.

**Comment by Tieske** [comment]
closing this for now.
