### ISSUE TITLE
bad number of arguments

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-pongo#369]
Most of the output formats seem to complain about a bad number of arguments. Even when running the example in the readme

```bash
pongo run -v -o gtest ./spec
```

```txl
gtest output handler: bad number of arguments: 0 argument(s) must be specified, not 1

Usage: gtest output handler [OPTIONS]

OPTIONS: 
  --color force use of color
  --plain force use of no color
```

What am I doing wrong here?

**Comment by esatterwhite** [comment]
A I see, its my `.busted` config

```lua
return {
  default = {
    ['verbose'] = true,
    ['coverage'] = true,
    ['output'] = "junit",
    ['Xoutput'] = {"/kong-plugin/coverage/test.xml"},
    ['ROOT'] = {"/kong-plugin/spec"}
  },
}
```

I used to be able to over ride this w/ just `pongo run -o gtest` and it didn't seem to care

**Comment by Tieske** [comment]
I think this is a busted issue. Probably best to report it there. The way the options for the output handlers are is awkward and sometimes (like in this case) problematic.
