### ISSUE TITLE
Support missing Kong EE 3.0.2.0 version

### ISSUE THREAD

**Issue by dol** [Kong/kong-pongo#371]
The Kong EE version [3.0.2.0](https://hub.docker.com/layers/kong/kong-gateway/3.0.2.0/images/sha256-d30241a7641b20f7501ad33a7cd0667e28efbf4a6e5faaf07e0c9332fc493fa8?context=explore) is currently not supported and is missing.

Could you please add it to the list of kong_versions. ❤

**Comment by Tieske** [comment]
just added to `master`, will be released shortly.

**Comment by Tieske** [comment]
Pongo `2.4.0` has been tagged and released.

**Comment by dol** [comment]
@Tieske 
🎉❤
Thank you. Much appreciated.

I guess since the Kong EE Github repository is private, the only possibility to get the spec files and helpers for Kong EE is through Pongo? As a reference: I'm use the spec files and helpers for our own internal tooling.

**Comment by Tieske** [comment]
Interesting, what are you trying to do that Pongo doesn't do already?

**Comment by dol** [comment]
We use a CI infrastructure that runs in Kubernetes. For that reason we are unable to use docker in pod. Because of this limitation we just use the spec helper files from this repository and install busted via luarocks.
