### ISSUE TITLE
Failed to build test environment

### ISSUE THREAD

**Issue by Raiyuki05** [Kong/kong-pongo#385]
We tried installing Pongo by following an installation guide from a Kong blog post and we encountered a build error upon running the pongo run command. Here is the link of the installation guide we followed:
https://konghq.com/blog/custom-lua-plugin-kong-gateway

Here are the exact commands we used:
PATH=$PATH:~/.local/bin
git clone https://github.com/Kong/kong-pongo.git
mkdir -p ~/.local/bin
ln -s $(realpath kong-pongo/pongo.sh) ~/.local/bin/pongo

Please see attached images for the errors.
![Build Error Forbidden IP](https://user-images.githubusercontent.com/119566385/221507514-bc17a974-1715-46cc-b992-a7bd47181e9f.png)

![Build Error 1](https://user-images.githubusercontent.com/119566385/221507545-3fd68de4-13a3-44f1-9ad4-ba81e281ab38.png)

![Build Error 2](https://user-images.githubusercontent.com/119566385/221507569-e6346442-fa34-40c6-8367-0a6587939602.PNG)

We tried to run the apt-get update --fix-missing, but when we ran the pongo run command, we encountered the same build error.

We appreciate your future responses. Thank you!

**Comment by Tieske** [comment]
seems like you don't have access to some resources. Is there a firewall in between that blocks access maybe?

**Comment by Raiyuki05** [comment]
> seems like you don't have access to some resources. Is there a firewall in between that blocks access maybe?

We already turned off the firewall but the issue still exists.
![Firewall disabled](https://user-images.githubusercontent.com/119566385/221521412-cae2b5b2-25ca-4edc-a9ce-393253585c29.png)

**Comment by Tieske** [comment]
iirc that's a local firewall, looks more like you're behind a corporate firewall

**Comment by Tieske** [comment]
Pongo copies these proxy variables; https://github.com/Kong/kong-pongo/blob/master/pongo.sh#L726-L729 
so make sure they are set

**Comment by Raiyuki05** [comment]
> Pongo copies these proxy variables; https://github.com/Kong/kong-pongo/blob/master/pongo.sh#L726-L729 so make sure they are set if needed

What do you mean by set it? Do you mean by adding links? or IP Address? Where can get and how can we set these variables?
    --build-arg http_proxy \
    --build-arg https_proxy \
    --build-arg ftp_proxy \
    --build-arg no_proxy \

Thank you!

**Comment by Tieske** [comment]
if you have them set on your host system, then when building the image, those variables will be copied from the host to the container (as in; the container "inherits" the settings from the host).

Typically if proxy/firewall is used then those environment variables are set to enable users to connect through the firewall/proxy using those settings.

**Comment by Raiyuki05** [comment]
> if you have them set on your host system, then when building the image, those variables will be copied from the host to the container (as in; the container "inherits" the settings from the host).
> 
> Typically if proxy/firewall is used then those environment variables are set to enable users to connect through the firewall/proxy using those settings.

Will look into this, we'll keep you posted. Thank you!

**Comment by Tieske** [comment]
clsoing due to no reponse
