### ISSUE TITLE
way to install test_dependencies

### ISSUE THREAD

**Issue by esatterwhite** [Kong/kong-pongo#387]
Is there a way to get pongo to install packages listed in `test_dependencies`? It seems to only pick up `dependencies`.
Maybe I'm missing something intrinsic to lua? Is it possible to include `test_dependencies` when pongo runs tests?

**Comment by Tieske** [comment]
what do you mean with `test_dependencies` ? That's not a Pongo thing is it?

**Comment by Tieske** [comment]
ah, it's luarocks, in the rockspec

**Comment by esatterwhite** [comment]
https://github.com/luarocks/luarocks/wiki/Rockspec-format#dependency-information

The rockspec format supports `dependencies` and `test_dependencies` things in `dependencies` seem to get installed when pongo runs. `test_dependencies` do not.

**Comment by Tieske** [comment]
But you can update the Pongo test initialization with a custom luarocks command that would do it for you

**Comment by esatterwhite** [comment]
Not familiar with that, example?

**Comment by Tieske** [comment]
here's the docs: https://github.com/Kong/kong-pongo#test-initialization

here's the default action: https://github.com/Kong/kong-pongo/blob/master/assets/default-pongo-setup.sh

**Comment by esatterwhite** [comment]
That did it, thanks!
