### ISSUE TITLE
Kong doesn't trust public CAs

### ISSUE THREAD

**Issue by mgugino-pdig** [Kong/kong-pongo#403]
Hello,

  Trying to use pongo to test a lua plugin for kong.  I am attempting to make an https request to an API.  It's failing with tls_process_server_certificate:certificate verify failed:unable to get local issuer certificate.
  
  I don't see a way to set kong's configuration with Pongo to remediate this problem.

I have tried setting
```
  export KONG_LUA_SSL_TRUSTED_CERTIFICATE=system
  export KONG_TEST_LUA_SSL_TRUSTED_CERTIFICATE=system
```
both prior to starting pongo, and in pongo shell prior to starting kong.

**Comment by Tieske** [comment]
can you provide a minimal example that reproduces the problem?

**Comment by mgugino-pdig** [comment]
So, what I found was TLS working is library dependent.  The plugin documentation doesn't really outline this, nor mention what libraries are generally available in the environment, but despite lua-http being present, it does not work:

```
local http_request = require "http.request"
local util = require('http.util')

local req = http_request.new_from_uri("https://some-well-known-api.example.com")

local headers, stream, number = req:go()
-- If there is a problem, headers will be nil, stream is actually an error, and number is error int.
if headers == nil then
  kong.log.debug("Error " .. stream)
end
```

This will show the TLS CA problem.

After some more searching, I saw that various plugins are using resty.http:

```
  local httpc = require("resty.http").new()

  -- Single-shot requests use the `request_uri` interface.
  local res, err = httpc:request_uri("https://some-well-known-api.example.com", {
      method = "POST",
  })
  ```
  
  In this case, TLS works normally.

**Comment by Tieske** [comment]
ok, that explains it. Do not use `lua-http` with OpenResty.

You can only use libraries that explicitly support OpenResty, the goto http-lib is indeed `resty.http`. That one will work.
