### ISSUE TITLE
Error with pongo up / run when disabling health checks

### ISSUE THREAD

**Issue by gorban** [Kong/kong-pongo#408]
## What I did

Installed:
* Docker from <https://download.docker.com/linux/static/stable/x86_64/>

Run pongo following [README.md section Disable Service Health Checks](https://github.com/Kong/kong-pongo#disable-service-health-checks):
```sh
export KONG_VERSION=3.3.0
export SERVICE_DISABLE_HEALTHCHECK=true
pongo build
sleep 10
pongo run
```

## What I expected

Pongo should have a successful run like it used to on [commit a268157910b50e2272be779eabb40d383d987b97](https://github.com/Kong/kong-pongo/commit/a268157910b50e2272be779eabb40d383d987b97).

## What actually happened

> ERROR: Service "expose" defines an invalid healthcheck: "disable: true" cannot be combined with other options

**Comment by hlreyes** [comment]
Looks like this error appears in the CI runs on this GitHub repo:  
<https://github.com/Kong/kong-pongo/actions/runs/5280495790/jobs/9552702493#step:5:2726>

**Comment by Tieske** [comment]
see also discussion here: https://github.com/Kong/kong-pongo/pull/405#issuecomment-1588862873

**Comment by gorban** [comment]
`docker version`

> Client: Docker Engine - Community
>  Version:           20.10.0
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        7287ab3
>  Built:             Tue Dec  8 18:54:00 2020
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.0
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       eeddea2
>   Built:            Tue Dec  8 18:58:04 2020
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          v1.4.3
>   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
>  runc:
>   Version:          1.0.0-rc92
>   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

`docker-compose version`

> docker-compose version 1.26.2, build unknown
> docker-py version: 4.4.4
> CPython version: 3.9.5
> OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

`docker compose version`

> docker: 'compose' is not a docker command.
> See 'docker --help'

**Comment by Tieske** [comment]
> Tue Dec 8 18:58:04 2020

that's two and a half years old.... can you try a newer version?

**Comment by gorban** [comment]
Instead of trying a newer version of `docker-compose` we installed the latest version of `docker compose` CLI plugin (we never had it installed before):

```sh
DOCKER_CONFIG=${DOCKER_CONFIG:-/usr/local/lib/docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
```

It looks like `kong-pongo` successfully found that one and used it instead. Not only do we get a successful `pongo up` + `pongo run` now, we were able to reenable the new health checks and it works too. We could also remove `sleep 10`:

```sh
export SERVICE_DISABLE_HEALTHCHECK=false
pongo up
# we have some other code in here that needs to find pongo-* Docker network so we can add a service for our tests...
pongo run
```

I am good, but I don't know if this issue should remain open in case a docker compose manifest could be used that is compatible with older docker-compose, or if that support should be dropped. I'll let whomever decide, but thank you all!

**Comment by Tieske** [comment]
@gorban thank you very much for reporting back ❤️ .

Now if you look at the compose file, then what happens is that everything gets rendered properly afaik, but compose seems to want no health-check details at all if you turn them off. Which in theory makes sense, but from a practical perspective makes it hard to quickly turn them on/off and try something new.

So I think we can safely close this, as it is solved in newer versions anyway.

**Comment by Tieske** [comment]
>  we have some other code in here that needs to find pongo-* Docker network so we can add a service for our tests...

fyi; you can add your own custom dependencies to Pongo by adding a compose snippet, see https://github.com/Kong/kong-pongo#custom-local-dependencies

**Comment by Tieske** [comment]
closing this, due to old docker-compose.
