### ISSUE TITLE
Pongo in dbless mode (--no-postgres) using kdbl is failing to recognize second custom plugin

### ISSUE THREAD

**Issue by sahsz123** [Kong/kong-pongo#479]
Hello,

Please note that I am running **_kong/kong-gateway:3.5.0.1-amazonlinux-2023_** image.

I've built an image with a custom plugin named jwk_collector with its source located in:
/usr/local/share/lua/5.1/kong/plugins/jwk_collector

And I am running Kong image 3.5.0.1/3.4.1.1 with it and developing one more plugin. Using DB-less mode (--no-postgres) with kdbl Kong reports that the plugin is not enabled:
```Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:184: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:793: error parsing declarative config file /kong-plugin/kong.yaml:
in 'services':
  - in entry 1 of 'services':
    in 'routes':
      - in entry 1 of 'routes':
        in 'plugins':
          - in entry 1 of 'plugins':
            in 'name': plugin 'jwk_collector' not enabled; add it to the 'plugins' configuration property
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:793: in function 'init'
	init_by_lua(nginx-kong.conf:60):3: in main chunk


  Run with --v (verbose) or --vv (debug) for more details
```
I am sourcing kong.conf and kong.yaml with the necessary configuration (e.g. jwk_collector -> enabled: true) before running kdbl
Kong.conf:
```
..
plugins = bundled,jwk_collector
```
and of course, the location has kong:kong perms:
```
/usr/local/share/lua/5.1/kong/plugins/jwk_collector
```

The Dockerfile for the image contains:

```
ENV KONG_PLUGINS=bundled,jwk_collector
```

**Comment by Tieske** [comment]
so you have 2 related custom plugins? that rely on each other?

Have you considered to put the two in the same repo? since they rely on each other anyway? In a default plugin structure, they are namespaced and can live next to eachother in the same repo.
Then you probably do not have to add anything, nor create a custom image. Pongo will insert and enable both plugins.

**Comment by sahsz123** [comment]
Well, I removed their dependency, so they run separately from one another. Now, I managed to get them in a single repo as your suggestion - Thank you!
I tried this before, but it didn't work. I did it now and it works!

**Comment by Tieske** [comment]
thx for reporting back.
