### ISSUE TITLE
[pongo-ERROR] Error: failed to build test environment 

### ISSUE THREAD

**Issue by mikyll** [Kong/kong-pongo#557]
I'm trying to learn how to use pongo for **custom plugin testing**. I created a new repository from the [kong-plugin](https://github.com/Kong/kong-plugin) template and followed [test run](https://github.com/Kong/kong-pongo?tab=readme-ov-file#do-a-test-run) instructions:

```sh
git clone https://github.com/Kong/kong-plugin.git
cd kong-plugin

# auto pull and build the test images
pongo run
```

But the command fails with this error:
```sh
[pongo-INFO] auto-starting the test environment, use the 'pongo down' action to stop it
[+] Running 2/2
 ✔ Network pongo-974422cb               Create...                          0.0s
 ✔ Container pongo-974422cb-postgres-1  Started                            0.0s
[pongo-INFO] Waiting for 'postgres' to become healthy
[pongo-INFO] image 'kong-pongo-2.10.0:3.6.1' not found, auto-building it
[pongo-INFO] starting build of image 'kong-pongo-2.10.0:3.6.1'
2024/04/29 12:47:34 http2: server: error reading preface from client //./pipe/do
cker_engine: file has already been closed
[+] Building 0.1s (6/27)                                         docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 3.08kB                                     0.0s
 => [internal] load metadata for docker.io/library/kong:3.6.1-ubuntu       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => CACHED [ 1/23] FROM docker.io/library/kong:3.6.1-ubuntu                0.0s
 => [internal] load build context                                          0.0s
 => => transferring context: 612B                                          0.0s
 => ERROR [ 2/23] COPY ./kong-versions/3.6.1/kong /kong                    0.0s
------
 > [ 2/23] COPY ./kong-versions/3.6.1/kong /kong:
------
Dockerfile:6
--------------------
   4 |     # add dev files
   5 |     ARG KONG_DEV_FILES
   6 | >>> COPY $KONG_DEV_FILES /kong
   7 |
   8 |     ARG PONGO_VERSION
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksu
m of ref eb74d5cb-2106-4d3c-b517-e419c116724b::cjshiuv76tim3jz87alia1dr1: "/kong
-versions/3.6.1/kong": not found

View build details: docker-desktop://dashboard/build/default/default/xihuwpwj640
ce24v1rbtbfi30
[pongo-ERROR] Error: failed to build test environment
```

Can someone help me understand why does that happen and how to solve it?

I'm using Git Bash (git version 2.42.0.windows.2) on Windows 10, and Docker Desktop v4.29.0

**Comment by Tieske** [comment]
what version of Pongo do you use? a specific version, or the `master` branch?

Can you try using a slightly older Pongo version, to validate that no recent changes caused this?

**Comment by mikyll** [comment]
@Tieske I I've found the issue: when I installed pongo I cloned the `master` branch (to be precise [commit 7d321f4](https://github.com/Kong/kong-pongo/commit/7d321f43e6938fee26121cb99350908193f39f36)) and followed the [installation instructions](https://github.com/Kong/kong-pongo?tab=readme-ov-file#installation). However, when launching the command, it would get stuck on:
```bash
/c/Users/mirighi/.local/bin/pongo: line 24: /c/Users/mirighi/.local/bin/assets/set_variables.sh: No such file or directory
/c/Users/mirighi/.local/bin/pongo: line 193: resolve_version: command not found
CreateFile C:\Users\mirighi\.local\bin\assets\docker-compose.yml: The system cannot find the path specified.
```

So I **copied the `assets/` directory** under `~/.local/bin/assets` and I was able to run `pongo --help`, but didn't continue with any testing (such as the plugin template).

---

I tried running the command directly from the directory where I cloned the repository and the command correctly builds the docker container 😃 

I don't know if mine was a common issue for Windows users, but maybe it can be addressed in some way 👀

**Comment by mikyll** [comment]
> ```shell
> /c/Users/mirighi/.local/bin/pongo: line 24: /c/Users/mirighi/.local/bin/assets/set_variables.sh: No such file or directory
> /c/Users/mirighi/.local/bin/pongo: line 193: resolve_version: command not found
> CreateFile C:\Users\mirighi\.local\bin\assets\docker-compose.yml: The system cannot find the path specified.
> ```

I think this is related to the differences in path formatting between Windows and Git Bash (Linux).

By the way, for the moment I solved by creating an **alias** instead of a symbolic link:

```
# file ~/.bashrc

alias pongo="/c/path/to/kong-pongo/pongo.sh"
```

**Comment by Tieske** [comment]
I noticed you have both Pongo and the plugin on the mounted drive; `/mnt/c/etc`, that might cause issues. If I run it all from the home directory in `wsl` it works for me. 

If I only have the plugin on the mounted drive I do get the existing "unix-socket" problem (known issue)
