### ISSUE TITLE
Kong 2.0.3 hasn't yet been published on dockerhub

### ISSUE THREAD

**Issue by nhynes** [Kong/kong-pongo#63]
#62 introduces support for Kong 2.0.3, but this causes build issues if using master, as [only 2.0.2](https://registry.hub.docker.com/_/kong/) is yet available on dockerhub. Certainly, this issue can be avoided by checking out a specific revision, but it might be more usable if this repo had tags for each supported Kong version.

**Comment by hutchic** [comment]
Waiting on Docker to review / merge https://github.com/docker-library/official-images/pull/7750

In the meantime we publish unofficial Docker Kong images at `kong/kong` along with daily builds when we do releases

https://hub.docker.com/r/kong/kong/tags?page=1&name=2.0.3

**Comment by Tieske** [comment]
@nhynes my bad, I merged the PR for 2.0.3 too soon. Will probably implement a fallback to an unoffical image (that doesn't have the review/merge lead-time) in the future to prevent this from happening again.

You can simply bypass by specifying the Kong version;

    KONG_VERSION=2.0.2 pongo run

**Comment by Tieske** [comment]
fyi fallback has been implemented. Just pull the latest Pongo.
