### ISSUE TITLE
running tests against custom plugins with dao

### ISSUE THREAD

**Issue by Abhishekvrshny** [Kong/kong-pongo#78]
_Not sure if this is the right forum to post, please redirect if not._

I have a custom plugin with a `dao` defined. I would like to run tests against it by inserting some values, similar to what's happening [here](https://github.com/Kong/kong/blob/master/spec/03-plugins/10-basic-auth/03-access_spec.lua#L67).
I could not find any documentation or example that seemed to do so for custom plugins. The blueprint defined in [fixtures](https://github.com/Kong/kong/blob/master/spec/fixtures/blueprints.lua#L83) has pre-defined `dao` objects. Can I add a custom `dao` object to this blueprint? If yes, how?

**Comment by Tieske** [comment]
the blue prints are a layer of magic on top of the DB layer. You can simply use the DB directly.

The blueprints inject some defaults, and wrap calls in assertions.

**Comment by Abhishekvrshny** [comment]
This works. Thanks a lot @Tieske !
